### ISSUE TITLE
getServerSideSitemap is being returned as undefined

### ISSUE THREAD

**Issue by lucascicco** [iamvishnusankar/next-sitemap#131] opened 2021-04-08 13:28 UTC
**Describe bugs**
getServerSideSitemap is not working as expected on generating sitemap for dynamic routes, even though I followed the process of implement it right, it does not work, it might be an exporting problem, cause it's undefined.

![image](https://user-images.githubusercontent.com/40899243/114034862-f5983580-9854-11eb-8e37-fde8ff4f9886.png)

**Comment by iamvishnusankar** [comment] 2021-04-09 01:52
@lucascicco Please provide a reproduction repo.

**Comment by lucascicco** [comment] 2021-04-09 21:55
@iamvishnusankar, I've just finished the reproduction repo, here goes the link: [repository](https://github.com/lucascicco/NEXT-SITEMAP-EXAMPLE)

Well, I've tested it and figured out that removing the "**module-resolver"** in the **babel.config.js** file solves the "bug", but it should not be like this, if you can take a try, thanks.

**Comment by sonnh58** [comment] 2021-06-18 03:55
same issue

**Comment by awadesmoline** [comment] 2021-08-06 10:26
same issue. and removing *module-resolver* cause errors importing svgs for me.

**Comment by petrkrizek** [comment] 2021-09-06 19:53
rename the root config file to custom name. Module resolver loads it instead of the package...

**Comment by hugoazevedosoares** [comment] 2021-09-21 18:18
I'm having the same problem in here. Did anyone else resolved without removing the module-loader?

**Comment by hugoazevedosoares** [comment] 2021-09-21 18:35
Ok, I have just renamed .babelrc to babelrc.js and it worked like magic.

**Comment by necheporenko** [comment] 2021-09-29 13:44
> rename the root config file to custom name. Module resolver loads it instead of the package...

What root config did you mean?

**Comment by necheporenko** [comment] 2021-09-29 13:56
> @iamvishnusankar, I've just finished the reproduction repo, here goes the link: [repository](https://github.com/lucascicco/next-sitemap-issue-reproduction)
> 
> Well, I've tested it and figured out that removing the "**module-resolver"** in the **babel.config.js** file solves the "bug", but it should not be like this, if you can take a try, thanks.

@lucascicco, Have you found a way to solve this problem?

**Comment by petrkrizek** [comment] 2021-09-29 17:40
> > rename the root config file to custom name. Module resolver loads it instead of the package...
> 
> @petrkrizek, What root config did you mean?

yes. The problem is, that module resolver probably tries to load next-sitemap.js config file from root of you project and not the module itself. Try to console.log the import. If you rename the config file to sth else like next-sitemap-config.js it should load the module. Of course you need to pass the correct config file to your postbuild npm command via `--config yourConfig.js`.

**Comment by lucascicco** [comment] 2021-10-05 10:43
@necheporenko Actually, I've found another way to reach the solution, it was removing the library from my project and doing it manually, if you are using next.js just add a new page called "sitemap.xml.ts", then you can use SSR to render it as you want, but remember to return the page as "xml". 
// https://cheatcode.co/tutorials/how-to-generate-a-dynamic-sitemap-with-next-js

**Closed** 2022-01-09 13:16 UTC
Labels: bug, missing reproduction
