### ISSUE TITLE
 robots.txt is not valid

### ISSUE THREAD

**Issue by mzaien** [iamvishnusankar/next-sitemap#197] opened 2021-07-28 23:09 UTC
**Describe the bug**
When i updated to the latest version the robot.txt was missing the production deployed to vercel
**To Reproduce**

1. Go to https://axenda-drive-droei2ydb-mzaien.vercel.app/
2. Sign in with google
2. open the chrome inspector
3. Run lighthouse test for SEO

**Expected behavior**
it should give me 100/100 in SEO, i tried to downgrade to previous version and everything is fine 

**Screenshots**
<img align="center" width="527" alt="CleanShot 2021-07-29 at 01 58 54@2x" src="https://user-images.githubusercontent.com/43112535/127407431-2d1ef60c-a435-42ab-a7b7-7b3d8b0e8de7.png">

**Additional context**
i'm using Next.js v11 and React 18

**Comment by renansigolo** [comment] 2021-08-22 10:29
I had the same issue @Mzaien and I was able to manually fix it by removing the **Host** field and according to [this article](https://developers.google.com/search/docs/advanced/robots/robots_txt#syntax) looks like google can't interpret this that.

But when looking at the [robots.txt documentation](http://www.robotstxt.org/orig.html#format) it mentions that **Unrecognised headers are ignored**. Moreover you can test it with a [robots.txt tester](https://support.google.com/webmasters/answer/6062598?hl=en) to verify that you don't have any warnings or erros, therefore the robots.txt generated by next-sitemap should be correct.

So after going through all of that I'm assuming that's an issue with the Lighthouse algorithm that's throwing an error when doesn't recognise a field, which in reality should actually be ignored.

Not sure what's the role of the host field though but in order to solve this next-sitemap could either completely remove this field from being generated or create an option to pass an optional flag to not generate the host field.

**Comment by MartinCura** [comment] 2021-08-31 20:53
I'm having the same problem (ruining a perfect Lighthouse score 😅). Haven't been able to understand what the problem is, having investigated the encoding and removing the Host fields to no avail. This makes me think it's a Lighthouse problem? But not sure. I even tried upgrading Chrome. My last bet would be in how the file is served.

**Comment by maxeth** [comment] 2021-09-27 09:51
Check out [this stackoverflow post](https://stackoverflow.com/questions/56441731/lighthouse-was-unable-to-download-a-robots-txt-file-despite-the-file-being-acc). It has been fixed on Chrome a long time ago apparently, but the issue is still present on some other browsers that use Chromium, such as the Brave Browser.

**Comment by renansigolo** [comment] 2021-09-29 00:57
Thank you so much for pointing that out @iamvishnusankar!

Best Regards,
Renan Sigolo

**Closed** 2022-01-07 04:57 UTC
Labels: bug
